# Generated by Django 3.1.5 on 2021-03-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_categoryattributeconfig'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytable',
            name='x_axis_attribute',
            field=models.ForeignKey(help_text='The attribute used to group products into columns on the table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_tables_x_axis', to='cms.attributetype', verbose_name='X Axis Attribute'),
        ),
    ]
