# Generated by Django 3.1.5 on 2021-03-30 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210330_1843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20210324_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGapAnalysisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('name', models.CharField(help_text='The name for this dashboard', max_length=100, verbose_name='Name')),
                ('brand', models.CharField(help_text='The brand analysed in the gap analysis report.', max_length=100, verbose_name='Brand')),
                ('category', models.ForeignKey(help_text='The category products should belong to in order to appear in the table.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.category', verbose_name='Category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('websites', models.ManyToManyField(help_text='Limit gap analysis report to these websites.', to='cms.Website', verbose_name='Websites')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
