# Generated by Django 3.1.5 on 2021-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_categorygapanalysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygapanalysisreport',
            name='price_clusters',
            field=models.JSONField(default=list, help_text='Price levels used to cluster products.', verbose_name='Price clusters'),
        ),
    ]
