# Generated by Django 3.1.5 on 2021-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20210410_1352'),
        ('dashboard', '0004_categorygapanalysisreport_price_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytable',
            name='brands',
            field=models.JSONField(blank=True, default=list, help_text='Only show products for these brands.', null=True, verbose_name='Brands'),
        ),
        migrations.AddField(
            model_name='categorytable',
            name='price_high',
            field=models.FloatField(blank=True, help_text='Only show products below this price', null=True, verbose_name='Price high'),
        ),
        migrations.AddField(
            model_name='categorytable',
            name='price_low',
            field=models.FloatField(blank=True, help_text='Only show products above this price', null=True, verbose_name='Price low'),
        ),
        migrations.AddField(
            model_name='categorytable',
            name='products',
            field=models.ManyToManyField(help_text='Only show these products.', to='cms.Product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='categorytable',
            name='websites',
            field=models.ManyToManyField(help_text='Only show products that are on these websites.', to='cms.Website', verbose_name='Websites'),
        ),
    ]
