# Generated by Django 3.1.5 on 2021-04-15 06:18

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20210410_1352'),
        ('dashboard', '0005_auto_20210412_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTableAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('attribute', models.ForeignKey(help_text='A spec to be displayed on the table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_table_attributes', to='cms.attributetype', verbose_name='Spec')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_table_attributes', to='dashboard.categorytable', verbose_name='Table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
