# Generated by Django 3.1.5 on 2021-04-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210420_1833'),
        ('dashboard', '0006_categorytableattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygapanalysisreport',
            name='brand',
            field=models.ForeignKey(help_text='The brand analysed in the gap analysis report.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.brand'),
        ),
        migrations.RemoveField(
            model_name='categorytable',
            name='brands',
        ),
        migrations.AddField(
            model_name='categorytable',
            name='brands',
            field=models.ManyToManyField(help_text='Only show products for these brands.', to='cms.Brand'),
        ),
    ]
