version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  cms:
    image: specr.azurecr.io/specr:deployment
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TEST_DB_NAME=test_cms
      - DEBUG=False
      - SECRET_KEY=khgfskhfuiwhwfkhfdkh
      - DJANGO_SETTINGS_MODULE=cms.production
      - CELERY_BROKER=amqp://guest:guest@celery-broker//
    volumes:
      - .:/app
      - cms-media:/app/cms/media
    ports:
      - "80:80"
    depends_on:
      - db

  celery-broker:
    image: rabbitmq:3.8.5-alpine

  celery-worker:
    image: specr.azurecr.io/specr:deployment
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG=False
      - CACHE_DURATION=30
      - HTTPCACHE_ENABLED=True
      - HTTPCACHE_EXPIRATION_SECS=604800
      - DJANGO_SETTINGS_MODULE=cms.production
      - CELERY_BROKER=amqp://guest:guest@celery-broker//
    restart: on-failure
    depends_on:
      - celery-broker
      - db
    volumes:
      - .:/app
      - cms-media:/app/cms/media
    command: ["celery", "-A", "cms", "worker", "-l", "DEBUG", "--concurrency", "1", "--events"]

  celery-beat:
    image: specr.azurecr.io/specr:deployment
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=cms.production
      - CELERY_BROKER=amqp://guest:guest@celery-broker//
    restart: on-failure
    depends_on:
      - celery-broker
    command: ["celery", "-A", "cms",  "beat", "-l", "DEBUG"]


volumes:
  db-data:
  cms-media:
  redis-data:
