version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - db-data:/var/lib/postgresql/data/
  cms:
    build: .
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TEST_DB_NAME=test_cms
      - DEBUG=True
      - GOOGLE_APPLICATION_CREDENTIALS=google-cloud-service-account-private-key.json
      - DIALOGFLOW_PROJECT_ID=specr-1612006278245
      - DIALOGFLOW_LANGUAGE_CODE=en
      - SESSION_ID=development
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5000:5000"
    depends_on:
      - db
  scraper:
    build:
      context: scraper
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=cms.settings
      - HTTPCACHE_ENABLED=True
      - HTTPCACHE_EXPIRATION_SECS=604800
      - DEBUG=True
    command: scrapy
    volumes:
      - .:/app
      - cms-media:/app/cms/media
    ports:
      - "6000:6000"
    depends_on:
      - db

volumes:
  db-data:
  cms-media:
  redis-data:
