version: "3.9"

services:
  cms:
    image: specr.azurecr.io/specr:deployment
    env_file:
      - .env
    volumes:
      - cms-media:/app/cms/media
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 2G
        limits:
          cpus: '1'
          memory: 3G

  celery-broker:
    image: rabbitmq:3.8.5-alpine
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '0.5'
          memory: 1.5G

  celery-worker:
    image: specr.azurecr.io/specr:deployment
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - celery-broker
    volumes:
      - cms-media:/app/cms/media
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '0.5'
          memory: 1.5G
    command: ["celery", "-A", "cms", "worker", "-l", "DEBUG", "--concurrency", "1", "--events"]

  celery-beat:
    image: specr.azurecr.io/specr:deployment
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - celery-broker
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '0.5'
          memory: 1.5G
    command: ["celery", "-A", "cms",  "beat", "-l", "DEBUG"]


volumes:
  cms-media:
    driver: azure_file
    driver_opts:
      share_name: cms-media
      storage_account_name: specr
  redis-data:
    driver: azure_file
    driver_opts:
      share_name: redis-data
      storage_account_name: specr
