version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  cms:
    build: .
    image: cms-image
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TEST_DB_NAME=test_cms
      - DEBUG=True
      - GOOGLE_APPLICATION_CREDENTIALS=google-cloud-service-account-private-key.json
      - DIALOGFLOW_PROJECT_ID=specr-1612006278245
      - DIALOGFLOW_LANGUAGE_CODE=en
      - SESSION_ID=development
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - DJANGO_SETTINGS_MODULE=cms.settings
      - AWS_CUSTOM_MEDIA_DOMAIN=localhost:9000
      - CELERY_BROKER=amqp://guest:guest@celery-broker//
    command: python3 manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
      - cms-media:/app/cms/media
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    command: minio server /data/minio/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  celery-broker:
    image: rabbitmq:3.8.5-alpine

  celery-worker:
    image: cms-image
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CACHE_DURATION=30
      - HTTPCACHE_ENABLED=True
      - HTTPCACHE_EXPIRATION_SECS=604800
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - DJANGO_SETTINGS_MODULE=cms.settings
      - CELERY_BROKER=amqp://guest:guest@celery-broker//
    restart: on-failure
    depends_on:
      - celery-broker
      - db
      - minio
    volumes:
      - .:/app
      - cms-media:/app/cms/media
    command: ["celery", "-A", "cms", "worker", "-l", "DEBUG", "--concurrency", "1", "--events"]

  celery-beat:
    image: cms-image
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=cms.settings
      - CELERY_BROKER=amqp://guest:guest@celery-broker//
    restart: on-failure
    depends_on:
      - celery-broker
    command: ["celery", "-A", "cms",  "beat", "-l", "DEBUG"]


volumes:
  db-data:
  cms-media:
  redis-data:
  minio-data:
