version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cms:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  scraper:
    build:
      context: scraper
      dockerfile: scraper/scraper/Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=cms.settings
      - HTTPCACHE_ENABLED=True
      - HTTPCACHE_EXPIRATION_SECS=604800
      - DEBUG=True
    command: scrapy
    volumes:
      - .:/app
    ports:
      - "6000:6000"
