# Generated by Django 3.1.5 on 2021-01-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210124_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedataitem',
            name='repeat',
            field=models.CharField(choices=[('once', 'Once'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', help_text='The frequency with which this data item should be tracked.', max_length=100, verbose_name='Repeat'),
        ),
    ]
