# Generated by Django 3.1.5 on 2021-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20210327_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='repeat',
            field=models.CharField(blank=True, choices=[('once', 'Once'), ('hour', 'Hourly'), ('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='once', help_text='The frequency with which this unit should be tracked.', max_length=100, null=True, verbose_name='Repeat'),
        ),
    ]
