# Generated by Django 3.1.5 on 2021-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210330_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattributeconfig',
            name='scoring',
            field=models.CharField(blank=True, choices=[('higher', 'Higher number value'), ('lower', 'Lower number value'), ('true', 'True boolean value'), ('false', 'False boolean value')], help_text='The mechanism by which values for this attribute should be scored.', max_length=100, null=True, verbose_name='Scoring'),
        ),
    ]
