# Generated by Django 3.1.5 on 2021-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20210410_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(help_text='The page url', max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
