# Generated by Django 3.1.5 on 2021-04-20 18:15

from django.db import migrations


def migrate_brands(apps, schema_editor):
    from cms.utils import migrate_brands_delete_attrs
    migrate_brands_delete_attrs(apps.get_model('cms', 'ProductAttribute'))


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20210420_1809'),
    ]

    operations = [
        migrations.RunPython(migrate_brands),
    ]
