# Generated by Django 3.1.5 on 2021-04-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20210410_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eprel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.eprelcategory', verbose_name='EPREL Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='eprel_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='EPREL Code'),
        ),
    ]
