# Generated by Django 3.1.5 on 2021-05-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210420_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category for this attribute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_types', to='cms.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together={('name', 'unit', 'category')},
        ),
    ]
