# Generated by Django 3.1.5 on 2021-05-01 10:52

from django.db import migrations


def migrate_attributes(apps, schema_editor):
    for attribute in apps.get_model('cms', 'AttributeType').objects.exclude(name__in=["price", "brand"]).all():
        attribute.category = attribute.productattributes.first().product.category
        attribute.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20210501_0933'),
    ]

    operations = [
        migrations.RunPython(migrate_attributes),
    ]
